name: Release

on:
  push:
    branches:
      - main

jobs:
  bump-version:
    name: Bump Version
    runs-on: ubuntu-latest
    concurrency: release
    permissions:
      id-token: write
      contents: write
    outputs:
      released: ${{ steps.python-semantic-release.outputs.released }}
      version: ${{ steps.python-semantic-release.outputs.version }}
      commit_sha: ${{ steps.sha.outputs.new_sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Python Semantic Release
        id: python-semantic-release
        uses: python-semantic-release/python-semantic-release@9.8.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get Commit SHA
        id: sha
        run: |
          new_sha=$(git rev-parse HEAD)
          echo $new_sha
          echo "new_sha=$new_sha" >> $GITHUB_OUTPUT
  docker:
    name: Docker Image
    runs-on: ubuntu-latest
    needs:
      - bump-version
    if: needs.bump-version.outputs.released == 'true'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.bump-version.outputs.commit_sha }}

      - name: Parse semantic version
        id: parse-semver
        run: |
          full_version=`echo ${{ needs.bump-version.outputs.version }}`
          major_version=`echo $full_version | cut -d'.' -f1`
          minor_version=`echo $full_version | cut -d'.' -f2`
          major_minor=`echo $major_version.$minor_version`
          echo "MAJOR_VERSION=$major_version" >> $GITHUB_OUTPUT
          echo "MAJOR_MINOR=$major_minor" >> $GITHUB_OUTPUT
          echo "FULL_VERSION=$full_version" >> $GITHUB_OUTPUT
